### ISSUE TITLE
Simplify /webrtc listen addr logic

### ISSUE THREAD

**Issue by MarcoPolo** [libp2p/js-libp2p-webrtc#113]
Shouldn't this be done by the library? Do we expect every user to do this?

_Originally posted by @MarcoPolo in https://github.com/libp2p/js-libp2p-webrtc/pull/90#discussion_r1145730071_

**Comment by achingbrain** [comment]
Fixed by https://github.com/libp2p/js-libp2p-webrtc/pull/166
