### ISSUE TITLE
Disconnection events are not emitted

### ISSUE THREAD

**Issue by marcus-pousette** [libp2p/js-libp2p-webrtc#138]
To reproduce 

Running the demo, put a log in ```node.addEventListener("peer:disconnect", ... ``` . The event is never emitted if one closes one of the tabs. 

This is creating severe issues for me when using this transport as I can not manage connections properly in my protocol handler.

**Comment by p-shahi** [comment]
@marcus-pousette We are aware of the issue and working on a fix here: https://github.com/libp2p/js-libp2p-webrtc/pull/134

**Comment by marcus-pousette** [comment]
> @marcus-pousette We are aware of the issue and working on a fix here: https://github.com/libp2p/js-libp2p-webrtc/pull/134

Aha! Great. I missed that. 

> The browser to browser demo?

Yes
