### ISSUE TITLE
Cannot find module 'eslint-plugin-n' 

### ISSUE THREAD

**Issue by marcus-pousette** [libp2p/js-libp2p-webrtc#159]
If you clone this repository, do ```yarn install``` and then ```yarn lint:fix``` you will run into following error message

```sh
Failed to load plugin 'n' declared in 'package.json » eslint-config-ipfs#overrides[1] » ./ts.js » eslint-config-standard-with-typescript » eslint-config-standard': Cannot find module 'eslint-plugin-n'
```

Has something changed with aegir? Perhaps old lock files make it work for developers who has cloned this repo earlier?

**Comment by marcus-pousette** [comment]
Does not fix it. I removed it and also removed the lock file and tried again. I also, vaguely, remember I had similar issue with the yamux lib

**Comment by achingbrain** [comment]
Interesting.  It's not missing though:

```console
% npm ls eslint-plugin-n
@libp2p/webrtc@1.2.0 /Users/alex/Documents/Workspaces/libp2p/js-libp2p-webrtc
└─┬ aegir@39.0.6
  └─┬ eslint-config-ipfs@4.0.2
    ├─┬ eslint-config-standard-with-typescript@34.0.1
    │ └── eslint-plugin-n@15.7.0
    └─┬ eslint-config-standard@17.0.0
      └── eslint-plugin-n@15.7.0 deduped
```

**Comment by marcus-pousette** [comment]
It works when I am doing ```npm install``` not ```yarn install```...  🤔

**Comment by marcus-pousette** [comment]
I created a issue in the aegir repo, because I get the same behaviour in the yamux lib now when I tested. https://github.com/ipfs/aegir/issues/1267
