### ISSUE TITLE
Dialling webrtc peers over webrtc-direct relay connection 

### ISSUE THREAD

**Issue by Marcel-G** [libp2p/js-libp2p-webrtc#171]
It's currently not possible to dial a peer over a relayed connection established with the `/webrtc-direct` transport.

For example, dialing a peer with the following multiaddr results in `CodeError: webrtc protocol was not present in multiaddr`

`/ip4/127.0.0.1/udp/9090/webrtc-direct/certhash/uEiBUr89tH2P9paTCPn-AcfVZcgvIvkwns96t4h55IpxFtA/p2p/12D3KooWB64sJqc3T3VCaubQCrfCvvfummrAA9z1vEXHJT77ZNJh/p2p-circuit/webrtc/p2p/12D3KooWFNBgv86tcpcYUHQz9FWGTrTmpMgr8feZwQXQySVTo3A7`

The problem lies in the [splitAddr](https://github.com/libp2p/js-libp2p-webrtc/blob/main/src/private-to-private/transport.ts#L76) function which breaks the addr up using `/webrtc` which incorrectly matches both `/webrtc-direct` and `/webrtc` transports.

**Comment by maschad** [comment]
Your listening multiaddr looks correct, could you share your JS node config along with some more info on how you are dialling that address? As I had mentioned on the [referenced issue](https://github.com/libp2p/rust-libp2p/issues/4017#issuecomment-1572350546) you could take a look at [universal connectivity](https://github.com/libp2p/universal-connectivity) to see how we where able to dial a browser node over webRTC using webRTCDirect as a relay.

**Comment by Marcel-G** [comment]
I suspect this particular issue is something introduced since `1.1.2`

https://github.com/libp2p/js-libp2p-webrtc/commit/b20875d9f73e5cad05376db2d1228363dd1bce7d#diff-ae86b5a052f8a01ec57238e9da2eca51b26220cf10e893315132f38887c13106L75

Sorry for linking these issues together as they're not really related in the end.

Regarding universal connectivity, In it's current state, the webrtc connections don't continue to work after the relay is closed / after the reservation has expired. Is that the same for you?

**Comment by maschad** [comment]
> I suspect this particular issue is something introduced since 1.1.2 https://github.com/libp2p/js-libp2p-webrtc/commit/b20875d9f73e5cad05376db2d1228363dd1bce7d#diff-ae86b5a052f8a01ec57238e9da2eca51b26220cf10e893315132f38887c13106L75 looks like an easy fix

You're correct, good catch! Thanks for opening the PR.
