### ISSUE TITLE
Implement write side congestion control

### ISSUE THREAD

**Issue by ckousik** [libp2p/js-libp2p-webrtc#40]
Implement response to backpressure from the receiver by checking the datachannel bufferedAmount and onBufferedAmountLow API.
pion example https://github.com/pion/webrtc/tree/master/examples/data-channels-flow-control

**Comment by ddimaria** [comment]
@ckousik is this something that we still want to do?

**Comment by ckousik** [comment]
Yes but this is not high priority.

**Comment by ckousik** [comment]
Closing since this is low priority. Will revisit once browser-to-browser is landed.
