### ISSUE TITLE
Export metrics

### ISSUE THREAD

**Issue by p-shahi** [libp2p/js-libp2p-webrtc#64]
### Done Criteria 

Export metrics leveraging the work done in https://github.com/libp2p/js-libp2p/issues/1458

### Motivation

Better observability for performance and benchmarking. See: https://github.com/libp2p/js-libp2p/issues/1458#issuecomment-1323833476 and https://github.com/libp2p/js-libp2p-tcp/pull/223/files

**Comment by ddimaria** [comment]
@p-shahi we can get someone to pick this up.  Alex is in the process of moving this repo to the libp2p org, so the work might be done there.  Someone will confirm when this is started.

**Comment by ddimaria** [comment]
@John-LittleBearLabs is picking this up.
