### ISSUE TITLE
PL code review

### ISSUE THREAD

**Issue by p-shahi** [libp2p/js-libp2p-webrtc#85]
### Done Criteria

PL review of the repo
- [x] Marco's 1st pass https://github.com/libp2p/js-libp2p-webrtc/pull/84
- [x] @achingbrain review (link to PR)

**Comment by achingbrain** [comment]
Changes after review:

* https://github.com/libp2p/js-libp2p-webrtc/pull/165
* https://github.com/libp2p/js-libp2p-webrtc/pull/166
* https://github.com/libp2p/js-libp2p-webrtc/pull/162
* https://github.com/libp2p/js-libp2p-webrtc/pull/160
