### ISSUE TITLE
Test example in CI

### ISSUE THREAD

**Issue by MarcoPolo** [libp2p/js-libp2p-webrtc#86]
We should test that the example works in all browsers as part of the CI job.

Here's js-libp2p-webtransport's workflow for the example: https://github.com/libp2p/js-libp2p-webtransport/blob/main/.github/workflows/examples.yml

and the test: https://github.com/libp2p/js-libp2p-webtransport/blob/main/examples/fetch-file-from-kubo/tests/test.js

**Comment by p-shahi** [comment]
@ckousik would you like to take this on?

**Comment by ckousik** [comment]
@p-shahi I'll be prioritizing circuit v2 right now. @ddimaria could help with prioritizing different tasks.

**Comment by ddimaria** [comment]
@MarcoPolo we may be limited with Go testing until the go-libp2p-webrtc PR is merged.  Do you think replacing that target with the Rust implementation would work (and is ready)?  We had an integration test in the repo previously, but were told to leverage Testground instead (and its successor).

**Comment by MarcoPolo** [comment]
>  We had an integration test in the repo previously

This isn't an integration test in the sense that we want to make sure `js-libp2p-webrtc` works. This should be to make sure we don't break the example, and that folks spinning up the example will have it work for them.

>  Do you think replacing that target with the Rust implementation would work

Maybe. The README.md mentions the Go server, so I would just stick to that.

I don't mind picking this up. I don't think it'll take very long. I made this issue simply to track, not to suggest LBL take it :)

**Comment by ddimaria** [comment]
@MarcoPolo I'm working on this now.

**Comment by p-shahi** [comment]
done in https://github.com/libp2p/js-libp2p-webrtc/pull/87

**Comment by eng-cc** [comment]
> Rust implementation

If we have Rust implementation, can we also add it to the example?

**Comment by ddimaria** [comment]
This issue is related to adding the existing example to CI (you may want to move this to a new issue if you want it tracked).  We haven't planned on adding a Rust implementation to the examples as the goal wasn't full interop but rather how to use the JS API.  That said, if you would like to create an issue for adding Rust and submit a PR, we'd happily merge it.
