### ISSUE TITLE
Will listen be supported for servers?

### ISSUE THREAD

**Issue by marcus-pousette** [libp2p/js-libp2p-webrtc#91]
I am working a [project](https://github.com/dao-xyz/peerbit) that heavily relies on the libp2p-js impl. I am currently working towards enabling a huge amount of dapps that benefit greatly from WebRTC. What I am missing (?) currently is a way for having js WebRTC listeners. Now it seems to only be supported/to-be-supported for the the Go and Rust impl. Correct me if I have understood the roadmap/spec.. incorrectly, but is this something that is planned for? Or not?

**Comment by mxinden** [comment]
For future us, cross-posting @MarcoPolo's comment here https://github.com/libp2p/specs/pull/412#issuecomment-1423211570.

**Comment by ddimaria** [comment]
@marcus-pousette you can track the progress of the browser-to-browser PR https://github.com/libp2p/js-libp2p-webrtc/pull/90, as well as the tracking issue https://github.com/libp2p/js-libp2p/issues/1462.
